import os
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

# Create reports folder automatically
REPORT_FOLDER = "reports"
os.makedirs(REPORT_FOLDER, exist_ok=True)


def generate_pdf(prediction, status, image_path, heatmap_path=None):
    """
    Generate a PDF report for Fake Media Detection.
    Heatmap is optional.
    """

    filename = f"Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    pdf_path = os.path.join(REPORT_FOLDER, filename)

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    # =====================================
    # Title
    # =====================================

    story.append(
        Paragraph(
            "<font size=20><b>Fake Media Detector Report</b></font>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # =====================================
    # Detection Details
    # =====================================

    story.append(
        Paragraph(
            f"<b>Prediction:</b> {prediction}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Status:</b> {status}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # =====================================
    # Uploaded Image
    # =====================================

    if image_path and os.path.exists(image_path):

        story.append(
            Paragraph("<b>Uploaded Image</b>", styles["Heading2"])
        )

        story.append(
            Image(image_path, width=220, height=220)
        )

        story.append(Spacer(1, 20))

    # =====================================
    # Heatmap (Optional)
    # =====================================

    if heatmap_path is not None:

        if os.path.exists(heatmap_path):

            story.append(
                Paragraph("<b>Grad-CAM Heatmap</b>", styles["Heading2"])
            )

            story.append(
                Image(heatmap_path, width=220, height=220)
            )

            story.append(Spacer(1, 20))

    # =====================================
    # Footer
    # =====================================

    story.append(
        Paragraph(
            "<b>Generated by AI Fake Media Detector</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)

    return filename